### ISSUE TITLE
[BUG]: Readme Format Script won't commit to PR

### ISSUE THREAD

**Issue by LelouchFR** [LelouchFR/skill-icons#145]
### Description of the bug

The Readme workflow does not work on other people than the maintainer (me), which is very strange...

### Steps To Reproduce

1. Open PR using a fork
2. Wait for jobs to run
3. If an icon has been added, it still says that it has nothing to commit
4. If no icon added, it will always return that it has nothing to commit

### Code of Conduct Acknowledgment

- [X] I have read and agree to the Code of Conduct.

**Comment by ghost** [comment]
Just an assumption, i was thinking maybe `git push` is causing that error, maybe specifying a branch will solve this `git push origin ${{ github.event.pull_request.head.ref }}`, tell me what do you think?

![Screenshot 2024-07-02 175215](https://github.com/LelouchFR/skill-icons/assets/170891407/e82dca6d-c7b7-4b92-a628-6217b50b8359)

**Comment by LelouchFR** [comment]
@sckoorp normally this should already put it in there:

```yml
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
```

but why not try it I guess

**Comment by ghost** [comment]
@LelouchFR You want me to do it on my pr or you will do it?

**Comment by LelouchFR** [comment]
> @LelouchFR You want me to do it on my pr or you will do it?

you can help me on the PR I opened (#140)

**Comment by ItsJoshBrown** [comment]
@LelouchFR  

After hours of digging into this  I did get this to work, However, I must admit, I'm still not entirely sure how it all works xD. The internet on this exact topic were all over the place with how to get it accomplished. xD. I thought I'd share with you, as you likely have more xp with GitHub Actions than I do. 


I cloned your repo over so I was able to use my accounts to fork as well and test. 

 - https://github.com/ItsJoshBrown/test_skill-icons/pull/8
 
 I did see once it commits the code it adds it directly to my forked Repo, and even though it says it needs approval it was still running before I clicked approve to run on my other account, so that could just be settings I have set up wrong or something. 

``` yml
name: Generate Readme

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set executable permission for script
        run: chmod +x ./.github/readme-format.sh

      - name: Run readme format script
        run: ./.github/readme-format.sh

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Format the readme file"
          git push origin HEAD:main
```
